### ISSUE TITLE
make check in skeletons fails to build on Mac

### ISSUE THREAD

**Issue by craig65535** [vlm/asn1c#228]
macOS 10.12.6, Xcode 9.0. `make check` fails in the skeletons dir on the master branch.

`ar cru` works on libasn1cskeletons_c89.a but then fails on libasn1cskeletons_c89_32.a because no archive members are specified.

```
/bin/sh ../libtool  --tag=CC   --mode=link gcc -std=c89 -Wpedantic -Wno-long-long  -fsanitize=undefined -fno-sanitize-recover=undefined -fsanitize=unsigned-integer-overflow -fno-sanitize
-recover=unsigned-integer-overflow -fsanitize=nullability -fno-sanitize-recover=nullability -fno-omit-frame-pointer -fsanitize=address -fno-omit-frame-pointer -g -O2 -Wall -Wcast-qual -W
char-subscripts -Wmissing-prototypes -Wmissing-declarations -Wno-error=attributes -Wno-error=cast-align -Wno-error=visibility -Wno-error=parentheses-equality -std=gnu99   -o libasn1cskel
etons_c89.la  libasn1cskeletons_c89_la-ANY.lo libasn1cskeletons_c89_la-BIT_STRING.lo libasn1cskeletons_c89_la-BIT_STRING_oer.lo libasn1cskeletons_c89_la-BMPString.lo libasn1cskeletons_c8
9_la-BOOLEAN.lo libasn1cskeletons_c89_la-ENUMERATED.lo libasn1cskeletons_c89_la-GeneralString.lo libasn1cskeletons_c89_la-GeneralizedTime.lo libasn1cskeletons_c89_la-GraphicString.lo lib
asn1cskeletons_c89_la-IA5String.lo libasn1cskeletons_c89_la-INTEGER.lo libasn1cskeletons_c89_la-INTEGER_oer.lo libasn1cskeletons_c89_la-ISO646String.lo libasn1cskeletons_c89_la-NULL.lo l
ibasn1cskeletons_c89_la-NativeEnumerated.lo libasn1cskeletons_c89_la-NativeEnumerated_oer.lo libasn1cskeletons_c89_la-NativeInteger.lo libasn1cskeletons_c89_la-NativeInteger_oer.lo libas
n1cskeletons_c89_la-NativeReal.lo libasn1cskeletons_c89_la-NumericString.lo libasn1cskeletons_c89_la-OBJECT_IDENTIFIER.lo libasn1cskeletons_c89_la-OCTET_STRING.lo libasn1cskeletons_c89_l
a-OCTET_STRING_oer.lo libasn1cskeletons_c89_la-OPEN_TYPE.lo libasn1cskeletons_c89_la-OPEN_TYPE_oer.lo libasn1cskeletons_c89_la-ObjectDescriptor.lo libasn1cskeletons_c89_la-PrintableStrin
g.lo libasn1cskeletons_c89_la-REAL.lo libasn1cskeletons_c89_la-RELATIVE-OID.lo libasn1cskeletons_c89_la-T61String.lo libasn1cskeletons_c89_la-TeletexString.lo libasn1cskeletons_c89_la-UT
CTime.lo libasn1cskeletons_c89_la-UTF8String.lo libasn1cskeletons_c89_la-UniversalString.lo libasn1cskeletons_c89_la-VideotexString.lo libasn1cskeletons_c89_la-VisibleString.lo libasn1cs
keletons_c89_la-asn_SEQUENCE_OF.lo libasn1cskeletons_c89_la-asn_SET_OF.lo libasn1cskeletons_c89_la-asn_application.lo libasn1cskeletons_c89_la-asn_codecs_prim.lo libasn1cskeletons_c89_la
-asn_internal.lo libasn1cskeletons_c89_la-asn_bit_data.lo libasn1cskeletons_c89_la-asn_random_fill.lo libasn1cskeletons_c89_la-ber_decoder.lo libasn1cskeletons_c89_la-ber_tlv_length.lo l
ibasn1cskeletons_c89_la-ber_tlv_tag.lo libasn1cskeletons_c89_la-constr_CHOICE.lo libasn1cskeletons_c89_la-constr_CHOICE_oer.lo libasn1cskeletons_c89_la-constr_SEQUENCE.lo libasn1cskeleto
ns_c89_la-constr_SEQUENCE_oer.lo libasn1cskeletons_c89_la-constr_SEQUENCE_OF.lo libasn1cskeletons_c89_la-constr_SET.lo libasn1cskeletons_c89_la-constr_SET_OF.lo libasn1cskeletons_c89_la-
constr_SET_OF_oer.lo libasn1cskeletons_c89_la-constr_TYPE.lo libasn1cskeletons_c89_la-constraints.lo libasn1cskeletons_c89_la-der_encoder.lo libasn1cskeletons_c89_la-oer_decoder.lo libas
n1cskeletons_c89_la-oer_encoder.lo libasn1cskeletons_c89_la-oer_support.lo libasn1cskeletons_c89_la-per_decoder.lo libasn1cskeletons_c89_la-per_encoder.lo libasn1cskeletons_c89_la-per_op
entype.lo libasn1cskeletons_c89_la-per_support.lo libasn1cskeletons_c89_la-xer_decoder.lo libasn1cskeletons_c89_la-xer_encoder.lo libasn1cskeletons_c89_la-xer_support.lo  
libtool: link: ar cru .libs/libasn1cskeletons_c89.a .libs/libasn1cskeletons_c89_la-ANY.o .libs/libasn1cskeletons_c89_la-BIT_STRING.o .libs/libasn1cskeletons_c89_la-BIT_STRING_oer.o .libs/libasn1cskeletons_c89_la-BMPString.o .libs/libasn1cskeletons_c89_la-BOOLEAN.o .libs/libasn1cskeletons_c89_la-ENUMERATED.o .libs/libasn1cskeletons_c89_la-GeneralString.o .libs/libasn1cskeletons_c89_la-GeneralizedTime.o .libs/libasn1cskeletons_c89_la-GraphicString.o .libs/libasn1cskeletons_c89_la-IA5String.o .libs/libasn1cskeletons_c89_la-INTEGER.o .libs/libasn1cskeletons_c89_la-INTEGER_oer.o .libs/libasn1cskeletons_c89_la-ISO646String.o .libs/libasn1cskeletons_c89_la-NULL.o .libs/libasn1cskeletons_c89_la-NativeEnumerated.o .libs/libasn1cskeletons_c89_la-NativeEnumerated_oer.o .libs/libasn1cskeletons_c89_la-NativeInteger.o .libs/libasn1cskeletons_c89_la-NativeInteger_oer.o .libs/libasn1cskeletons_c89_la-NativeReal.o .libs/libasn1cskeletons_c89_la-NumericString.o .libs/libasn1cskeletons_c89_la-OBJECT_IDENTIFIER.o .libs/libasn1cskeletons_c89_la-OCTET_STRING.o .libs/libasn1cskeletons_c89_la-OCTET_STRING_oer.o .libs/libasn1cskeletons_c89_la-OPEN_TYPE.o .libs/libasn1cskeletons_c89_la-OPEN_TYPE_oer.o .libs/libasn1cskeletons_c89_la-ObjectDescriptor.o .libs/libasn1cskeletons_c89_la-PrintableString.o .libs/libasn1cskeletons_c89_la-REAL.o .libs/libasn1cskeletons_c89_la-RELATIVE-OID.o .libs/libasn1cskeletons_c89_la-T61String.o .libs/libasn1cskeletons_c89_la-TeletexString.o .libs/libasn1cskeletons_c89_la-UTCTime.o .libs/libasn1cskeletons_c89_la-UTF8String.o .libs/libasn1cskeletons_c89_la-UniversalString.o .libs/libasn1cskeletons_c89_la-VideotexString.o .libs/libasn1cskeletons_c89_la-VisibleString.o .libs/libasn1cskeletons_c89_la-asn_SEQUENCE_OF.o .libs/libasn1cskeletons_c89_la-asn_SET_OF.o .libs/libasn1cskeletons_c89_la-asn_application.o .libs/libasn1cskeletons_c89_la-asn_codecs_prim.o .libs/libasn1cskeletons_c89_la-asn_internal.o .libs/libasn1cskeletons_c89_la-asn_bit_data.o .libs/libasn1cskeletons_c89_la-asn_random_fill.o .libs/libasn1cskeletons_c89_la-ber_decoder.o .libs/libasn1cskeletons_c89_la-ber_tlv_length.o .libs/libasn1cskeletons_c89_la-ber_tlv_tag.o .libs/libasn1cskeletons_c89_la-constr_CHOICE.o .libs/libasn1cskeletons_c89_la-constr_CHOICE_oer.o .libs/libasn1cskeletons_c89_la-constr_SEQUENCE.o .libs/libasn1cskeletons_c89_la-constr_SEQUENCE_oer.o .libs/libasn1cskeletons_c89_la-constr_SEQUENCE_OF.o .libs/libasn1cskeletons_c89_la-constr_SET.o .libs/libasn1cskeletons_c89_la-constr_SET_OF.o .libs/libasn1cskeletons_c89_la-constr_SET_OF_oer.o .libs/libasn1cskeletons_c89_la-constr_TYPE.o .libs/libasn1cskeletons_c89_la-constraints.o .libs/libasn1cskeletons_c89_la-der_encoder.o .libs/libasn1cskeletons_c89_la-oer_decoder.o .libs/libasn1cskeletons_c89_la-oer_encoder.o .libs/libasn1cskeletons_c89_la-oer_support.o .libs/libasn1cskeletons_c89_la-per_decoder.o .libs/libasn1cskeletons_c89_la-per_encoder.o .libs/libasn1cskeletons_c89_la-per_opentype.o .libs/libasn1cskeletons_c89_la-per_support.o .libs/libasn1cskeletons_c89_la-xer_decoder.o .libs/libasn1cskeletons_c89_la-xer_encoder.o .libs/libasn1cskeletons_c89_la-xer_support.o 
libtool: link: ranlib .libs/libasn1cskeletons_c89.a
libtool: link: ( cd ".libs" && rm -f "libasn1cskeletons_c89.la" && ln -s "../libasn1cskeletons_c89.la" "libasn1cskeletons_c89.la" )
/bin/sh ../libtool  --tag=CC   --mode=link gcc  -g -O2 -Wall -Wcast-qual -Wchar-subscripts -Wmissing-prototypes -Wmissing-declarations -Wno-error=attributes -Wno-error=cast-align -Wno-error=visibility -Wno-error=parentheses-equality -std=gnu99   -o libasn1cskeletons_c89_32.la    
libtool: link: ar cru .libs/libasn1cskeletons_c89_32.a 
ar: no archive members specified
usage:  ar -d [-TLsv] archive file ...
        ar -m [-TLsv] archive file ...
        ar -m [-abiTLsv] position archive file ...
        ar -p [-TLsv] archive [file ...]
        ar -q [-cTLsv] archive file ...
        ar -r [-cuTLsv] archive file ...
        ar -r [-cuTLsv] archive file ...
        ar -r [-abciuTLsv] position archive file ...
        ar -t [-TLsv] archive [file ...]
        ar -x [-ouTLsv] archive [file ...]
make[1]: *** [libasn1cskeletons_c89_32.la] Error 1
make: *** [check-am] Error 2
```

**Comment by craig65535** [comment]
This works in v0.9.28.

**Comment by velichkov** [comment]
Hi @craig65535,

Apply this patch and try to configure with and without `--disable-test-32bit`
[skeletons_32bit.txt](https://github.com/vlm/asn1c/files/1412825/skeletons_32bit.txt)

**Comment by craig65535** [comment]
@velichkov with the patch applied, it works with and without passing --disable-test-32bit to configure.

**Comment by craig65535** [comment]
@velichkov did you want to make a PR for that patch, or should I do it?

**Comment by craig65535** [comment]
Thanks @velichkov

**Comment by mouse07410** [comment]
I've tried the current master with and without #229, with and without `--disable-test-32bit`. Two tests inevitably fail:
```
. . . . .
============================================================================
Testsuite summary for asn1c 0.9.29
============================================================================
# TOTAL: 40
# PASS:  40
# SKIP:  0
# XFAIL: 0
# FAIL:  0
# XPASS: 0
# ERROR: 0
============================================================================
Making check in tests-randomized
/Applications/Xcode.app/Contents/Developer/usr/bin/make  check-bundles.sh
make[3]: Nothing to be done for `check-bundles.sh'.
/Applications/Xcode.app/Contents/Developer/usr/bin/make  check-TESTS
PASS: bundles/00-NULL-bundle.txt
PASS: bundles/01-BOOLEAN-bundle.txt
PASS: bundles/02-INTEGER-bundle.txt
PASS: bundles/03-ENUMERATED-bundle.txt
PASS: bundles/04-REAL-bundle.txt
PASS: bundles/05-BIT-STRING-bundle.txt
PASS: bundles/06-OCTET-STRING-bundle.txt
PASS: bundles/07-VisibleString-bundle.txt
PASS: bundles/08-OBJECT-IDENTIFIER-bundle.txt
PASS: bundles/09-RELATIVE-OID-bundle.txt
PASS: bundles/10-UTF8String-bundle.txt
PASS: bundles/11-BMPString-bundle.txt
PASS: bundles/12-UniversalString-bundle.txt
PASS: bundles/13-UTCTime-bundle.txt
PASS: bundles/14-GeneralizedTime-bundle.txt
PASS: bundles/15-CHOICE-bundle.txt
PASS: bundles/16-SEQUENCE-bundle.txt
FAIL: bundles/17-SEQUENCE-OF-bundle.txt
FAIL: bundles/19-SET-OF-bundle.txt
============================================================================
Testsuite summary for asn1c 0.9.29
============================================================================
# TOTAL: 19
# PASS:  17
# SKIP:  0
# XFAIL: 0
# FAIL:  2
# XPASS: 0
# ERROR: 0
============================================================================
See tests/tests-randomized/test-suite.log
Please report to vlm@lionet.info
============================================================================
make[4]: *** [test-suite.log] Error 1
make[3]: *** [check-TESTS] Error 2
make[2]: *** [check-am] Error 2
make[1]: *** [check-recursive] Error 1
make: *** [check-recursive] Error 1
```

Here's the `tests/tests-randomized/test-suite.log` file: 
[randomized-test-suite.log.txt](https://github.com/vlm/asn1c/files/1415959/randomized-test-suite.log.txt)

**Comment by velichkov** [comment]
@mouse07410 

> I've tried the current master with and without #229, with and without --disable-test-32bit

Which versions of `MacOS`, `XCode` and `ar` are you testing with? 

> Here's the tests/tests-randomized/test-suite.log file:

Same failures as in the TravisCI, could you try with my latest commit 18ee1fb3b24369478359ca9fc2017e49f9aeb729?

**Comment by mouse07410** [comment]
> Which versions of MacOS, XCode and ar are you testing with?

MacOS 10.12.6 Sierra, Xcode-9.0.1. I didn't install any special `ar`, so whatever came with macOS+Xcode is it.

> Same failures as in the TravisCI, 

I feel like I'm in a good company. ;-)

> could you try with my latest commit 18ee1fb?

Sure, will try tomorrow.

**Comment by mouse07410** [comment]
@vlm please re-open. The problem remains:
```
. . . . .
============================================================================
Testsuite summary for asn1c 0.9.29
============================================================================
# TOTAL: 40
# PASS:  40
# SKIP:  0
# XFAIL: 0
# FAIL:  0
# XPASS: 0
# ERROR: 0
============================================================================
Making check in tests-randomized
/Applications/Xcode.app/Contents/Developer/usr/bin/make  check-bundles.sh
make[3]: Nothing to be done for `check-bundles.sh'.
/Applications/Xcode.app/Contents/Developer/usr/bin/make  check-TESTS
PASS: bundles/00-NULL-bundle.txt
PASS: bundles/01-BOOLEAN-bundle.txt
PASS: bundles/02-INTEGER-bundle.txt
PASS: bundles/03-ENUMERATED-bundle.txt
PASS: bundles/04-REAL-bundle.txt
PASS: bundles/05-BIT-STRING-bundle.txt
PASS: bundles/06-OCTET-STRING-bundle.txt
PASS: bundles/07-VisibleString-bundle.txt
PASS: bundles/08-OBJECT-IDENTIFIER-bundle.txt
PASS: bundles/09-RELATIVE-OID-bundle.txt
PASS: bundles/10-UTF8String-bundle.txt
PASS: bundles/11-BMPString-bundle.txt
PASS: bundles/12-UniversalString-bundle.txt
PASS: bundles/13-UTCTime-bundle.txt
PASS: bundles/14-GeneralizedTime-bundle.txt
PASS: bundles/15-CHOICE-bundle.txt
PASS: bundles/16-SEQUENCE-bundle.txt
FAIL: bundles/17-SEQUENCE-OF-bundle.txt
FAIL: bundles/19-SET-OF-bundle.txt
============================================================================
Testsuite summary for asn1c 0.9.29
============================================================================
# TOTAL: 19
# PASS:  17
# SKIP:  0
# XFAIL: 0
# FAIL:  2
# XPASS: 0
# ERROR: 0
============================================================================
See tests/tests-randomized/test-suite.log
Please report to vlm@lionet.info
============================================================================
make[4]: *** [test-suite.log] Error 1
make[3]: *** [check-TESTS] Error 2
make[2]: *** [check-am] Error 2
make[1]: *** [check-recursive] Error 1
make: *** [check-recursive] Error 1
```

[randomized-test-suite.log.txt](https://github.com/vlm/asn1c/files/1419467/randomized-test-suite.log.txt)

**Comment by craig65535** [comment]
@mouse07410 that was failing for me and now works. Silly question but did you start fresh (git clean and autoreconf)?

**Comment by mouse07410** [comment]
1. Did it fail for you the same way (aka in the same place) as in my example?

2. I always start with `autoreconf`, but I did not do `git clean`.

**Comment by craig65535** [comment]
I remember it failing towards the end of tests-randomized, on both my Mac and a CentOS 7 VM, for the past few weeks. #229 seems to have fixed it.

Since this was build-related, I started fresh after pulling from master (`git checkout -- . && git clean -f -x -d -- . && autoreconf -i`)

**Comment by mouse07410** [comment]
Funny. I tried on a different machine (that also exhibited this problem), and the tests passed. Thanks for bringing up `git clean`.

**Comment by vlm** [comment]
make clean usually works for me, no git clean or autoreconf is needed in most cases.

Does this problem remain or is it fixed?

**Comment by mouse07410** [comment]
> make clean usually works for me, no git clean or autoreconf is needed in most cases.

I concur, and never tried `git clean` before. With asn1c I usually do `make distclean` and/or autoreconf, to make sure no artifacts from prior builds could interfere.

> Does this problem remain or is it fixed?

@vlm On one of the two machines I'm running this, your master branch passed all the tests. On the other machine the problem remains. Both machines run macOS 10.12.6 with Xcode-9.0.1.

**Comment by vlm** [comment]
What does tests/tests-randomized/test-suite.log say about it? The last 50 lines should help.

**Comment by mouse07410** [comment]
Last 50 lines of test-suite.log say
```
$ tail -50 ~/Downloads/randomized-test-suite.log.txt 
    WWSEOLXNWZCBGSUMCACUBISZHXLWGTZOGFXNFEQ
    BFZTBZZAYOBYHFKGNYECAOKXRABYRAMNEBZCLWSKAZAAUYEVPAUYBBZZVQQJFAODRUZJKHGXEIAZQPXIQK
    EWZZAYJHBYUQBRYMKOMAZZJJYCJZQBSYWWCA
    RYYZFBRUAMARZYMZTBYPNVLFWPZAZZIFADCKUBEQYYZX
    RDLZBBBVSHAMKZZKBUVKAYPLRYCVCMCSJQLCHAIHYAMNMGSYXJOKZEXCOPAAGLVW
    YZYYAYOEPJNBDLRYVYITEVUPYBPTYANYKQZBCMPGAVBZZBTVRBJYQMQARZBBZGQNOFFDCFBRVZZHBLYBCLHAOSAZBY
    CZASRYABDUBJADANXDYSVBYQSMIYFYDP
    GABRIQJAAZRTDFPYINAAETGGAKGBBAEEJBDISSSRKZBIXYSCZPKFTUEASGUOHJXBASDBBKLGMJTRYLYHADQM
    YANBTBZSPUBVYCYVCAZYCUVBPJZVMMFACBPANEZBYZZBBYCBMKRABHAKZAKYMZICYWRRYFAIBABUZYJARPBSMROYZHAV
    DBIYVADYYZZNCKAGYBBZBDXYSBAIJXSMVDAUAULAJSAEABAYBDSEIBFBBZBKIBAYUOZEFEHTRRVABYMYAZIOZYYAPFIQNEBYUKLATSGZBPBM
    TYYJMINYLZZVYPYJNPCKZYAASESLLBVZZTYABMBYBTOYUHHBBZMMGBBBNVSPRAZFBAABLAZUFBUSYVOVGTUVAXPWYETAV
    ZEYYBADCAUYUCBBWAJNOVSMZVMAZECPUCLCYABWWBEBZBDKZFPQPOBSMAOASLZIAAZPZAGYCOZAJBDFCYRXADXCYY
    ZQADHGMADSYBXYOLMBRLHBAYEGJTATBBOXKAYZMDCMRLRBYSBDXZDBVYYFTQWQVAASZAPQDZFJPNKGVQXOOEYTXKQTZJTAZJZBOYQGDNWEOOX
    GZMJXZYDYTCAABDCAVGAHBEDBIRSHUMHAFSPKHPAHDGNEUZAFIJYJFQMKAYYEYRBBZVPBLQ
    GZSAHFIS
    AEYLUJAYMBETDGYZEARZKLBUYBLMUVYAAAJERAWTZWQEXPIHZBYTHXXBVFKIOVOAYJMABXOXPYMPBN
    SZOTERZONAHJDYEEZXATWZCABXPJMHHYHLVMKABOBSSABLSEOBPPABNA
    WWAOQZBTYJNYEBQHVMXYABALDAZBEZNBEPHYMYBNLRQUJARJFGQYRDYYFYYBYZBZJURAHCZHZBCSZAZLULXZQWWPUZRSJDNWCBYWLUZWTZBQIFOBQNUPXZYMQN
    BGNTEMIGDVQAALYARMUPVTGLRBYZRGABCWWJKAZAZRTFYZJOFXNPYZZKBDYW
    SBCYGEUGSZPBBZQAILPGXZZIFNYXKMXZANZCOESBBOYPKYXRRZGJAD
    KRYWZOYBGABKGFRIVGAMZJVGYYZLQVKWTHZZ
    AOXKZKJBYMSKVFXVDXAHYYXRLFAAAYWPOWXAZGASTCZBRDUAZTOLYYAOERZAUDKEKJVOIMZAZPFPJZNDDFFGS
    EITBNKYUYORNQQZXKWNXASPRWZYWCFADZJPTQHSOBHWKIABYVCSAAZHOMIBTEBEDYA
    OTHMJOAERBVBBGYBPBSUWZBQPNDRTFAAYHZABPFNPDDJAZZSSGYDXBKVHHCRBXAHAZUTDSSYJOZAMIPFJQEROP
    PBBZGJHZGFMXIRJUBIPOPUEKGZZBYMJFYBKKASLPBGEMPTCIAUBYQIFRBIFZGHYZIYV
    XLMGIPZZZKPYEHJZAZTCSJYYALETIAOLIJBFDPAMBZSZAYKTOSAQEYHAJJVVYGOAYAZSVBBZBCYNZSQJTOOUPWZHSKAHHFCAOIJB
    UBQZHCAPQYZMFCROTSLAQAAIVAACIXYRMUKJCUQZHNBJZHTOZGZAZAATVYYEFJAFZYPPYUDBYZVZSJLABFMZBEHNTOIIQYBXINLOYRTXJAAYTB
    DBPYOYOVAZJZZUBRYOEYWSTPZZGZBUZYKHAWZCLGZBBURPPBYFFZYKEQBZARJYUYMKYFYBDZZKIODZZYAOJJVXYVNYKBBZDGZNWQXNMZPXPQKVZBZGOZCNQHFTKMOTYBZMSDZYAHQDPBZAUAYRIHNXAFYETMDSSZVZQZJHZQDDNVDRZX
    PSYYBBJAXHGDOUYYBXZOJGGUNZDZKYAABNYKKAUNAJHBMBYZTKVRXZKCWJXOGGATKAHPQIARACEKYQZLOAVAOKWGPNOZRDPWPKUPTZBZYKAXYZZTZQHYAZSVCSYYPUHMGYEURZDBQSSJKYHKTYYYAXANZBLSTC
    LVXTPIAFQLOGYLZNZOXNYYOZHIPXGVBFTCBZNFZGDAVKKFAPIXKEBJALITAHXASNYCEEQ
    
    DLABALBYRZUANBDZJSVZPAMNHBNAZAUGSAZBKIJTNKDGWADOQDFCEAMBBJYUSZIBTTPFBMVUIKMFYNAYWZLDSSUALTYTJVMKBCZNMQGDBGTTBDKDLTSBSDOMSYSBOBZALBXFLURFKBYAXDBHIZUUECYCBXGYTZQBVFUDUZYZKYCBFBWZEZAIUHZAWSLBHVEGABTZIIBBZQPAEMBGMLXYX
    ARKZYMYASYNZJFBBFWWEAGCLBGIZBHZXEAYZNABAWPIZDRLYZYYPVYFXEQOYAOBUURGFMYXIPKJBLZZZGVTWDAJIZXRVZEPDYYQAXHSXAKVVWHEBSAVWHBMBYSBJEZTAHFFMKXKPXBHBKMVUYAPQZPRIRBZFZZFNUHGNUCIBYLBTZYARSDGBYRBAZADHGZPYFTEPCY
    ZXVNGSQXQYZZYHWX
}
+ echo RETRY:
RETRY:
+ cat .test-reproduce
(cd ".tmp.17-SEQUENCE-OF-bundle" && CC=clang CFLAGS="-std=gnu99 -Wno-error=unused-variable  -fsanitize=undefined -fno-sanitize-recover=undefined -fsanitize=unsigned-integer-overflow -fno-sanitize-recover=unsigned-integer-overflow -fsanitize=nullability -fno-sanitize-recover=nullability -fno-omit-frame-pointer -fsanitize=address -fno-omit-frame-pointer -maes -mpclmul -msse2 -mssse3 -msse4 -msse4.2 -mrdrnd -mrdseed -Os -Ofast -Wall -Wcast-qual -Wchar-subscripts -Wmissing-prototypes -Wmissing-declarations -Wno-error=attributes -Wno-error=cast-align -Wno-error=visibility -Wno-error=parentheses-equality -std=gnu99" /Applications/Xcode.app/Contents/Developer/usr/bin/make &&  ./random-test-driver -s 70000  -c)
+ return 3
++ expr 0 + 1
+ tests_failed=1
+ echo 'FAIL [T ::= SEQUENCE OF BOOLEAN -- RMAX=70000] in ./bundles/17-SEQUENCE-OF-bundle.txt 31'
FAIL [T ::= SEQUENCE OF BOOLEAN -- RMAX=70000] in ./bundles/17-SEQUENCE-OF-bundle.txt 31
+ '[' 1 = 1 ']'
+ echo 'STOP after 1 failures, OK 25'
STOP after 1 failures, OK 25
+ exit 1
FAIL bundles/17-SEQUENCE-OF-bundle.txt (exit status: 1)

$ 
```

And this text in the log was preceded by:
```
+ short_asn='SEQUENCE OF BOOLEAN'
+ test '!' -f Makefile.am
+ asn1c_invoke test.asn1 'T ::= SEQUENCE OF BOOLEAN -- RMAX=70000' 'in ./bundles/17-SEQUENCE-OF-bundle.txt 31' -flink-skeletons
+ tmpfile=test.asn1
+ asn='T ::= SEQUENCE OF BOOLEAN -- RMAX=70000'
+ where='in ./bundles/17-SEQUENCE-OF-bundle.txt 31'
+ shift 3
+ echo 'Test DEFINITIONS ::= BEGIN T ::= SEQUENCE OF BOOLEAN -- RMAX=70000'
+ echo '-- in ./bundles/17-SEQUENCE-OF-bundle.txt 31'
+ echo END
+ echo '/Users/ur20980/src/asn1c-vlm/asn1c/asn1c -S /Users/ur20980/src/asn1c-vlm/skeletons'
/Users/ur20980/src/asn1c-vlm/asn1c/asn1c -S /Users/ur20980/src/asn1c-vlm/skeletons
+ /Users/ur20980/src/asn1c-vlm/asn1c/asn1c -S /Users/ur20980/src/asn1c-vlm/skeletons -gen-OER -gen-PER -flink-skeletons test.asn1
Compiled T.c
Compiled T.h
File /Users/ur20980/src/asn1c-vlm/skeletons/BOOLEAN.h is already here as BOOLEAN.h
File /Users/ur20980/src/asn1c-vlm/skeletons/BOOLEAN.c is already here as BOOLEAN.c
File /Users/ur20980/src/asn1c-vlm/skeletons/asn_SEQUENCE_OF.h is already here as asn_SEQUENCE_OF.h
File /Users/ur20980/src/asn1c-vlm/skeletons/asn_SEQUENCE_OF.c is already here as asn_SEQUENCE_OF.c
File /Users/ur20980/src/asn1c-vlm/skeletons/asn_SET_OF.h is already here as asn_SET_OF.h
File /Users/ur20980/src/asn1c-vlm/skeletons/asn_SET_OF.c is already here as asn_SET_OF.c
File /Users/ur20980/src/asn1c-vlm/skeletons/constr_SEQUENCE_OF.h is already here as constr_SEQUENCE_OF.h
File /Users/ur20980/src/asn1c-vlm/skeletons/constr_SEQUENCE_OF.c is already here as constr_SEQUENCE_OF.c
File /Users/ur20980/src/asn1c-vlm/skeletons/constr_SET_OF.h is already here as constr_SET_OF.h
File /Users/ur20980/src/asn1c-vlm/skeletons/constr_SET_OF.c is already here as constr_SET_OF.c
File /Users/ur20980/src/asn1c-vlm/skeletons/asn_application.h is already here as asn_application.h
File /Users/ur20980/src/asn1c-vlm/skeletons/asn_application.c is already here as asn_application.c
File /Users/ur20980/src/asn1c-vlm/skeletons/asn_ioc.h is already here as asn_ioc.h
File /Users/ur20980/src/asn1c-vlm/skeletons/asn_system.h is already here as asn_system.h
File /Users/ur20980/src/asn1c-vlm/skeletons/asn_codecs.h is already here as asn_codecs.h
File /Users/ur20980/src/asn1c-vlm/skeletons/asn_internal.h is already here as asn_internal.h
File /Users/ur20980/src/asn1c-vlm/skeletons/asn_internal.c is already here as asn_internal.c
File /Users/ur20980/src/asn1c-vlm/skeletons/asn_random_fill.h is already here as asn_random_fill.h
File /Users/ur20980/src/asn1c-vlm/skeletons/asn_random_fill.c is already here as asn_random_fill.c
File /Users/ur20980/src/asn1c-vlm/skeletons/asn_bit_data.h is already here as asn_bit_data.h
File /Users/ur20980/src/asn1c-vlm/skeletons/asn_bit_data.c is already here as asn_bit_data.c
File /Users/ur20980/src/asn1c-vlm/skeletons/OCTET_STRING.h is already here as OCTET_STRING.h
File /Users/ur20980/src/asn1c-vlm/skeletons/OCTET_STRING.c is already here as OCTET_STRING.c
File /Users/ur20980/src/asn1c-vlm/skeletons/BIT_STRING.h is already here as BIT_STRING.h
File /Users/ur20980/src/asn1c-vlm/skeletons/BIT_STRING.c is already here as BIT_STRING.c
File /Users/ur20980/src/asn1c-vlm/skeletons/asn_codecs_prim.c is already here as asn_codecs_prim.c
File /Users/ur20980/src/asn1c-vlm/skeletons/asn_codecs_prim.h is already here as asn_codecs_prim.h
File /Users/ur20980/src/asn1c-vlm/skeletons/ber_tlv_length.h is already here as ber_tlv_length.h
File /Users/ur20980/src/asn1c-vlm/skeletons/ber_tlv_length.c is already here as ber_tlv_length.c
File /Users/ur20980/src/asn1c-vlm/skeletons/ber_tlv_tag.h is already here as ber_tlv_tag.h
File /Users/ur20980/src/asn1c-vlm/skeletons/ber_tlv_tag.c is already here as ber_tlv_tag.c
File /Users/ur20980/src/asn1c-vlm/skeletons/ber_decoder.h is already here as ber_decoder.h
File /Users/ur20980/src/asn1c-vlm/skeletons/ber_decoder.c is already here as ber_decoder.c
File /Users/ur20980/src/asn1c-vlm/skeletons/der_encoder.h is already here as der_encoder.h
File /Users/ur20980/src/asn1c-vlm/skeletons/der_encoder.c is already here as der_encoder.c
File /Users/ur20980/src/asn1c-vlm/skeletons/constr_TYPE.h is already here as constr_TYPE.h
File /Users/ur20980/src/asn1c-vlm/skeletons/constr_TYPE.c is already here as constr_TYPE.c
File /Users/ur20980/src/asn1c-vlm/skeletons/constraints.h is already here as constraints.h
File /Users/ur20980/src/asn1c-vlm/skeletons/constraints.c is already here as constraints.c
File /Users/ur20980/src/asn1c-vlm/skeletons/xer_support.h is already here as xer_support.h
File /Users/ur20980/src/asn1c-vlm/skeletons/xer_support.c is already here as xer_support.c
File /Users/ur20980/src/asn1c-vlm/skeletons/xer_decoder.h is already here as xer_decoder.h
File /Users/ur20980/src/asn1c-vlm/skeletons/xer_decoder.c is already here as xer_decoder.c
File /Users/ur20980/src/asn1c-vlm/skeletons/xer_encoder.h is already here as xer_encoder.h
File /Users/ur20980/src/asn1c-vlm/skeletons/xer_encoder.c is already here as xer_encoder.c
File /Users/ur20980/src/asn1c-vlm/skeletons/per_support.h is already here as per_support.h
File /Users/ur20980/src/asn1c-vlm/skeletons/per_support.c is already here as per_support.c
File /Users/ur20980/src/asn1c-vlm/skeletons/per_decoder.h is already here as per_decoder.h
File /Users/ur20980/src/asn1c-vlm/skeletons/per_decoder.c is already here as per_decoder.c
File /Users/ur20980/src/asn1c-vlm/skeletons/per_encoder.h is already here as per_encoder.h
File /Users/ur20980/src/asn1c-vlm/skeletons/per_encoder.c is already here as per_encoder.c
File /Users/ur20980/src/asn1c-vlm/skeletons/per_opentype.h is already here as per_opentype.h
File /Users/ur20980/src/asn1c-vlm/skeletons/per_opentype.c is already here as per_opentype.c
Symlinked /Users/ur20980/src/asn1c-vlm/skeletons/converter-example.c	-> converter-example.c
File /Users/ur20980/src/asn1c-vlm/skeletons/oer_decoder.h is already here as oer_decoder.h
File /Users/ur20980/src/asn1c-vlm/skeletons/oer_decoder.c is already here as oer_decoder.c
File /Users/ur20980/src/asn1c-vlm/skeletons/OPEN_TYPE.h is already here as OPEN_TYPE.h
File /Users/ur20980/src/asn1c-vlm/skeletons/oer_encoder.h is already here as oer_encoder.h
File /Users/ur20980/src/asn1c-vlm/skeletons/oer_encoder.c is already here as oer_encoder.c
File /Users/ur20980/src/asn1c-vlm/skeletons/oer_support.h is already here as oer_support.h
File /Users/ur20980/src/asn1c-vlm/skeletons/oer_support.c is already here as oer_support.c
File /Users/ur20980/src/asn1c-vlm/skeletons/OPEN_TYPE_oer.c is already here as OPEN_TYPE_oer.c
File /Users/ur20980/src/asn1c-vlm/skeletons/constr_CHOICE.h is already here as constr_CHOICE.h
File /Users/ur20980/src/asn1c-vlm/skeletons/INTEGER_oer.c is already here as INTEGER_oer.c
File /Users/ur20980/src/asn1c-vlm/skeletons/INTEGER.h is already here as INTEGER.h
File /Users/ur20980/src/asn1c-vlm/skeletons/OCTET_STRING_oer.c is already here as OCTET_STRING_oer.c
File /Users/ur20980/src/asn1c-vlm/skeletons/NativeInteger_oer.c is already here as NativeInteger_oer.c
File /Users/ur20980/src/asn1c-vlm/skeletons/NativeInteger.h is already here as NativeInteger.h
File /Users/ur20980/src/asn1c-vlm/skeletons/NativeEnumerated_oer.c is already here as NativeEnumerated_oer.c
File /Users/ur20980/src/asn1c-vlm/skeletons/NativeEnumerated.h is already here as NativeEnumerated.h
File /Users/ur20980/src/asn1c-vlm/skeletons/constr_SEQUENCE_oer.c is already here as constr_SEQUENCE_oer.c
File /Users/ur20980/src/asn1c-vlm/skeletons/constr_SEQUENCE.h is already here as constr_SEQUENCE.h
File /Users/ur20980/src/asn1c-vlm/skeletons/constr_CHOICE_oer.c is already here as constr_CHOICE_oer.c
File /Users/ur20980/src/asn1c-vlm/skeletons/constr_SET_OF_oer.c is already here as constr_SET_OF_oer.c
File /Users/ur20980/src/asn1c-vlm/skeletons/BIT_STRING_oer.c is already here as BIT_STRING_oer.c
Generated Makefile.am.targets
Generated Makefile.am.example
+ echo 'ASN.1 compiled OK'
ASN.1 compiled OK
+ '[' 0 '!=' 0 ']'
+ rm -f converter-example.c
+ ln -sf .././random-test-driver.c
+ echo 'CFLAGS+= -DASN1_TEXT='\''SEQUENCE OF BOOLEAN'\'''
+ echo 'ASN_PROGRAM = random-test-driver'
+ echo 'ASN_PROGRAM_SOURCES = random-test-driver.c'
+ echo
+ echo 'include Makefile.am.example'
+ echo
+ echo 'all-tests-succeeded: /Users/ur20980/src/asn1c-vlm/asn1c/asn1c $(ASN_PROGRAM_SOURCES) $(ASN_MODULE_SOURCES) $(ASN_MODULE_HEADERS)'
+ echo '	@rm -f $@'
+ echo '	@echo Previous try did not go correctly. To reproduce:'
+ echo '	@cat .test-reproduce'
+ echo '	@exit 1'
+ echo
+ echo 'Makefile.am.example -> Makefile'
Makefile.am.example -> Makefile
+ '[' 0 -ne 0 ']'
+ rm -f random-test-driver.o
+ rm -f random-test-driver
+ CFLAGS='-std=gnu99 -Wno-error=unused-variable  -fsanitize=undefined -fno-sanitize-recover=undefined -fsanitize=unsigned-integer-overflow -fno-sanitize-recover=unsigned-integer-overflow -fsanitize=nullability -fno-sanitize-recover=nullability -fno-omit-frame-pointer -fsanitize=address -fno-omit-frame-pointer -maes -mpclmul -msse2 -mssse3 -msse4 -msse4.2 -mrdrnd -mrdseed -Os -Ofast -Wall -Wcast-qual -Wchar-subscripts -Wmissing-prototypes -Wmissing-declarations -Wno-error=attributes -Wno-error=cast-align -Wno-error=visibility -Wno-error=parentheses-equality -std=gnu99'
+ Make
+ /Applications/Xcode.app/Contents/Developer/usr/bin/make -j 1
clang -std=gnu99 -Wno-error=unused-variable  -fsanitize=undefined -fno-sanitize-recover=undefined -fsanitize=unsigned-integer-overflow -fno-sanitize-recover=unsigned-integer-overflow -fsanitize=nullability -fno-sanitize-recover=nullability -fno-omit-frame-pointer -fsanitize=address -fno-omit-frame-pointer -maes -mpclmul -msse2 -mssse3 -msse4 -msse4.2 -mrdrnd -mrdseed -Os -Ofast -Wall -Wcast-qual -Wchar-subscripts -Wmissing-prototypes -Wmissing-declarations -Wno-error=attributes -Wno-error=cast-align -Wno-error=visibility -Wno-error=parentheses-equality -std=gnu99 -DASN1_TEXT='SEQUENCE OF BOOLEAN'  -I. -o random-test-driver.o -c random-test-driver.c
clang -std=gnu99 -Wno-error=unused-variable  -fsanitize=undefined -fno-sanitize-recover=undefined -fsanitize=unsigned-integer-overflow -fno-sanitize-recover=unsigned-integer-overflow -fsanitize=nullability -fno-sanitize-recover=nullability -fno-omit-frame-pointer -fsanitize=address -fno-omit-frame-pointer -maes -mpclmul -msse2 -mssse3 -msse4 -msse4.2 -mrdrnd -mrdseed -Os -Ofast -Wall -Wcast-qual -Wchar-subscripts -Wmissing-prototypes -Wmissing-declarations -Wno-error=attributes -Wno-error=cast-align -Wno-error=visibility -Wno-error=parentheses-equality -std=gnu99 -DASN1_TEXT='SEQUENCE OF BOOLEAN'  -I.  -o random-test-driver random-test-driver.o  libasncodec.a -lm
+ '[' 0 -ne 0 ']'
++ get_param RMAX 128 'T ::= SEQUENCE OF BOOLEAN -- RMAX=70000'
++ param=RMAX
++ default=128
++ asn='T ::= SEQUENCE OF BOOLEAN -- RMAX=70000'
++ nawk ''
++ AWK=awk
++ echo 'T ::= SEQUENCE OF BOOLEAN -- RMAX=70000'
++ awk 'BEGIN{FS="[^RMAX=0-9]+"};/RMAX=/{for(i=1;i<=NF;i++)if(substr($i,0,length("RMAX="))=="RMAX=")PARAM=substr($i,length("RMAX=")+1)}END{if(PARAM)print PARAM;else print "128";}'
+ rmax=70000
+ '[' 070000 -lt 1 ']'
+ echo 'Checking random data encode-decode'
Checking random data encode-decode
+ round_trip_check_cmd=' ./random-test-driver -s 70000  -c'
+ echo '(cd ".tmp.17-SEQUENCE-OF-bundle" && CC=clang CFLAGS="-std=gnu99 -Wno-error=unused-variable  -fsanitize=undefined -fno-sanitize-recover=undefined -fsanitize=unsigned-integer-overflow -fno-sanitize-recover=unsigned-integer-overflow -fsanitize=nullability -fno-sanitize-recover=nullability -fno-omit-frame-pointer -fsanitize=address -fno-omit-frame-pointer -maes -mpclmul -msse2 -mssse3 -msse4 -msse4.2 -mrdrnd -mrdseed -Os -Ofast -Wall -Wcast-qual -Wchar-subscripts -Wmissing-prototypes -Wmissing-declarations -Wno-error=attributes -Wno-error=cast-align -Wno-error=visibility -Wno-error=parentheses-equality -std=gnu99" /Applications/Xcode.app/Contents/Developer/usr/bin/make &&  ./random-test-driver -s 70000  -c)'
+ eval ' ./random-test-driver -s 70000  -c'
++ ./random-test-driver -s 70000 -c
Testing 100 iterations of round-trip for DER
[000] round-trip in 2 bytes OK
[001] round-trip in 37333 bytes OK
[002] round-trip in 69114 bytes OK
[003] round-trip in 65103 bytes OK
[004] round-trip in 104980 bytes OK
... and so on
OK 100 iterations of round-trip for DER
Testing 100 iterations of round-trip for OER
[000] round-trip in 2 bytes OK
[001] round-trip in 2 bytes OK
[002] round-trip in 44370 bytes OK
[003] round-trip in 2 bytes OK
[004] round-trip in 78934 bytes OK
... and so on
OK 100 iterations of round-trip for OER
Testing 100 iterations of round-trip for UPER
Decoding 64530 bytes of T yielded RC_FAIL after byte 0
Original random structure:
T ::= {
    
    PGU
    VRT
    

```
[t.log.txt](https://github.com/vlm/asn1c/files/1423736/t.log.txt)

**Comment by vlm** [comment]
asn1c regenerates `T.c` in a way that the change is invisible to the `make`. Therefore make doesn't recompile `T.o`, `libasncodec.a`, and the program itself.

Likely fixed in https://github.com/vlm/asn1c/commit/f22184d31ca3bc808cc156b47fd5320658623c66, please enjoy!

**Comment by mouse07410** [comment]
@vlm I'm afraid it's still a problem. Preliminary run on my fastest machine (macOS 10.12.6,  Xcode-9.0.1) shows
```
. . . . .
PASS: bundles/16-SEQUENCE-bundle.txt
FAIL: bundles/17-SEQUENCE-OF-bundle.txt
FAIL: bundles/19-SET-OF-bundle.txt
============================================================================
Testsuite summary for asn1c 0.9.29
============================================================================
# TOTAL: 19
# PASS:  17
# SKIP:  0
# XFAIL: 0
# FAIL:  2
# XPASS: 0
# ERROR: 0
============================================================================
See tests/tests-randomized/test-suite.log
Please report to vlm@lionet.info
============================================================================
make[4]: *** [test-suite.log] Error 1
make[3]: *** [check-TESTS] Error 2
```

Currently doing a "perfectly-clean" test-run (wiped out everything, fresh-cloned your master, started from scratch).

**Comment by mouse07410** [comment]
###Update 2

Ont he slowest machine it appears to work. On the fastest machine it still fails two last randomized tests consistently. On a moderately fast machine (on which I originally reported this) it just passed all the tests.

**Comment by velichkov** [comment]
Hi @mouse07410,

https://github.com/vlm/asn1c/blob/f22184d31ca3bc808cc156b47fd5320658623c66/tests/tests-randomized/check-bundles.sh#L61

It seems that removing the T object file was not enough, change it to `rm -f T.* || : ` and try again.
Do you have `ccache` installed and do you use it?
If yes try to disable it with `export CCACHE_DISABLE=1`

P.S.
When you edit a comment the github does not send email notifications so the updates may pass unnoticed.

**Comment by brchiu** [comment]
Hi, folks, 
On my laptop, Ubuntu 17.10 run on i7-6700HQ, `make check` fails at test `FAIL: bundles/05-BIT-STRING-bundle.txt`. 

The last lines of `tests-suite.log` before failure message :  https://gist.github.com/brchiu/c5d0309fbc0c54d49979daf15f7b1404

For your information.

**Comment by mouse07410** [comment]
> It seems that removing the T object file was not enough, change it to `rm -f T.* || :` and try again.

@velichkov thank you - all tests passed on the fastest machine. Tomorrow will check on the other one.

**Comment by velichkov** [comment]
@brchiu 

> On my laptop, Ubuntu 17.10 run on i7-6700HQ, make check fails at test FAIL: bundles/05-BIT-STRING-bundle.txt.

It seems awk `substr` is not fully compatible between various versions of `awk`, `nawk`, `makw`, `gawk` ...
Could you try with the following patch applied?

```patch
diff --git a/tests/tests-randomized/check-bundles.sh b/tests/tests-randomized/check-bundles.sh
index d3c7247b..ed05a922 100755
--- a/tests/tests-randomized/check-bundles.sh
+++ b/tests/tests-randomized/check-bundles.sh
@@ -146,7 +146,7 @@ get_param() {
         AWK=awk
     fi
 
-    echo "$asn" | ${AWK} "BEGIN{FS=\"[^${param}=0-9]+\"};/$param=/{for(i=1;i<=NF;i++)if(substr(\$i,0,length(\"${param}=\"))==\"${param}=\")PARAM=substr(\$i,length(\"${param}=\")+1)}END{if(PARAM)print PARAM;else print \"${default}\";}"
+    echo "$asn" | ${AWK} "BEGIN{FS=\"[^${param}=0-9]+\"};/$param=/{for(i=1;i<=NF;i++)if(substr(\$i,1,length(\"${param}=\"))==\"${param}=\")PARAM=substr(\$i,length(\"${param}=\")+1)}END{if(PARAM)print PARAM;else print \"${default}\";}"
 }
 
 # compile_and_test "<text>" "<where found>"
```

@mouse07410 

>  thank you - all tests passed on the fastest machine. Tomorrow will check on the other one.

Great, but what about `ccache`?

**Comment by brchiu** [comment]
@velichkov , 
Great ! After applying your patch, the very first time all these 19 randomized test cases pass on my laptop. 
I check my system by `update-alternative --list awk` and it shows `/usr/bin/mawk` is used.
Thank you very much !   :smiley:

**Comment by mouse07410** [comment]
> Great, but what about `ccache`?

Not used.

On the "main" macOS machine, it failed this morning. Same two last tests in the "randomized" bundle. I applied your AWK patch, and restarted.

**Comment by velichkov** [comment]
> On the "main" macOS machine, it failed this morning. Same two last tests in the "randomized" bundle. I applied your AWK patch, and restarted.
> After restart, one last test fails:

Maybe we need to remove the `libasncodec.a` together with the T.* files because the T.o is actually added in the static lib. Could you try it?

**Comment by velichkov** [comment]
Or better try to remove only the T.o and libasncodec.a because after removing the T.[ch] the code coverage decreased a little compared to the current master. https://coveralls.io/jobs/30766132/source_files/1958903183#L386

**Comment by mouse07410** [comment]
"Main" machine: tests pass successfully. Consistently. One more machine to go.

**Comment by mouse07410** [comment]
On the fastest machine: everything's fine. All tests pass successfully.

I think your fix is complete now.

**Comment by vlm** [comment]
Fixed, thank you!

**Comment by mouse07410** [comment]
Fix confirmed. Thanks!
